version: '3'

services:
  postgres:
    image: 'postgres:13'
    container_name: 'java-postgres'
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER= postgres
      - POSTGRES_DB= postgres
      - POSTGRES_PASSWORD= qqq
    volumes:
      - "db-data:/var/lib/postgresql/data"




  #services:
  wallet-app:
    build:
      context: .
      dockerfile: Dockerfile
    #    image: wallet-app:latest
    ports:
      - "8080:8080"
    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/java
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: qqq
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
    #      SPRING_LIQUIBASE_ENABLED: true
    depends_on:
      - postgres

volumes:
  db-data:
#
#  postgres:
#    image: 'postgres:latest'
#    environment:
#      POSTGRES_USER: Ivan
#      POSTGRES_PASSWORD: "170494jggjam"
#      POSTGRES_DB: MyWalet
#    volumes:
#      - postgres:/var/lib/postgresql/data
#    ports:
#      - "5432:5432"